# Generated by Django 5.2.8 on 2025-11-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ct",
            fields=[
                ("id_ct", models.AutoField(primary_key=True, serialize=False)),
                ("nome_ct", models.CharField(max_length=100)),
                ("capacidade_ct", models.IntegerField()),
                ("cep", models.CharField(blank=True, max_length=9, null=True)),
                ("rua", models.CharField(blank=True, max_length=200, null=True)),
                ("numero_rua", models.CharField(blank=True, max_length=10, null=True)),
                ("bairro", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
