# Generated by Django 5.2.8 on 2025-11-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cidadao",
            fields=[
                ("id_cidadao", models.AutoField(primary_key=True, serialize=False)),
                ("nome_cidadao", models.CharField(max_length=256)),
                ("cpf_cidadao", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("email_cidadao", models.EmailField(max_length=254, unique=True)),
                ("telefone_cidadao", models.CharField(max_length=15)),
                ("cep_cidadao", models.CharField(max_length=9)),
                ("rua_cidadao", models.CharField(max_length=200)),
                ("numero_rua_cidadao", models.CharField(max_length=10)),
                ("bairro_cidadao", models.CharField(max_length=100)),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cidadão",
                "verbose_name_plural": "Cidadãos",
                "ordering": ["nome_cidadao"],
            },
        ),
    ]
