# Generated by Django 5.2.8 on 2025-11-11 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ct", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                ("id_modalidade", models.AutoField(primary_key=True, serialize=False)),
                ("nome_modalidade", models.CharField(max_length=256)),
                ("regras_modalidade", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CT_Modalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vagas_disponiveisMod", models.IntegerField(default=35)),
                ("horarios_oferecidos", models.CharField(max_length=256)),
                ("dias_na_semana", models.CharField(max_length=100)),
                (
                    "ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modalidades",
                        to="ct.ct",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cts",
                        to="modalidades.modalidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "CT - Modalidade",
                "verbose_name_plural": "CTs - Modalidades",
                "unique_together": {("ct", "modalidade")},
            },
        ),
    ]
