# Generated by Django 5.2.8 on 2025-11-11 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cidadaos", "0001_initial"),
        ("ct", "0001_initial"),
        ("modalidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                            ("lista_espera", "Lista de Espera"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status da Inscrição",
                    ),
                ),
                (
                    "data_incricao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Inscrição"
                    ),
                ),
                (
                    "data_confirmacao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Confirmação"
                    ),
                ),
                (
                    "data_cancelamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Cancelamento"
                    ),
                ),
                (
                    "numero_protocolo",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        unique=True,
                        verbose_name="Número do Protocolo",
                    ),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(blank=True, verbose_name="Motivo do Cancelamento"),
                ),
                (
                    "cidadao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="cidadaos.cidadao",
                    ),
                ),
                (
                    "ct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="ct.ct",
                        verbose_name="Centro de Treinamento",
                    ),
                ),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="modalidades.modalidade",
                        verbose_name="Modalidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição",
                "verbose_name_plural": "Inscrições",
                "ordering": ["-data_incricao"],
                "unique_together": {("cidadao", "modalidade")},
            },
        ),
    ]
