# Generated by Django 5.2.8 on 2025-11-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrutor",
            fields=[
                ("id_instrutor", models.AutoField(primary_key=True, serialize=False)),
                ("nome_instrutor", models.CharField(max_length=256)),
                ("cpf_instrutor", models.CharField(max_length=14, unique=True)),
                ("email_instrutor", models.EmailField(max_length=254, unique=True)),
                ("telefone_instrutor", models.CharField(max_length=15)),
            ],
        ),
    ]
